framework:
    messenger:
        failure_transport: failed

        transports:
            # 1. Transport pour les EMAILS (Utilise Redis)
            email_transport:
                dsn: '%env(MESSENGER_TRANSPORT_EMAIL_DSN)%'
                
            # 2. Transport pour les TÂCHES LOURDES (Utilise Beanstalkd)
            async_app_transport:
                dsn: '%env(MESSENGER_TRANSPORT_APP_DSN)%'
              
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # ssl:
                    #     allow_self_signed: true
                    #     capture_peer_cert: true
                    #     capture_peer_cert_chain: true
                    #     disable_compression: true
                    #     SNI_enabled: true
                    #     verify_peer: true
                    #     verify_peer_name: true
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: email_transport
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
