sonata_admin:
    title: 'ORIND AFRICA'
    title_logo: 'images/logo.jpg'
    show_mosaic_button: false
    options:
        js_debug: true 
    templates:
        layout: 'bundles/SonataAdminBundle/standard_layout.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.user:
                label: app.admin.group.user
                translation_domain: Admin
                icon: fas fa-users
                # items:
                #    - App\Infrastructure\Admin\User\AdminUserAdmin
                roles: ['ROLE_ADMIN','ROLE_MEMBER']
            app.admin.group.domain_group.action:
                label: app.admin.group.domain_group.action
                translation_domain: Admin
                icon: fas fa-sitemap

            app.admin.group.permission.manager:
                label: app.admin.group.permission.manager
                translation_domain: Admin
                icon: fas fa-user-shield
                roles: ['ROLE_ADMIN']

    default_controller: App\UI\Http\Controller\Admin\WlindablaAdminCRUDController.php
    # default_admin_services:
    #     security_handler: App\Infrastructure\Security\Handler\RoleSecurityHandler
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, HISTORY, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]