vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       profile:
           uri_prefix: /media/profile
           upload_destination: '%kernel.project_dir%/public/media/profile'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       document:
           uri_prefix: /media/document
           upload_destination: '%kernel.project_dir%/public/media/document'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
    
